configs:
  searxng_inline_settings:
    content: |
      use_default_settings: true
      search:
        formats:
          - html
          - json

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    hostname: searxng
    container_name: searxng
    pull_policy: always
    restart: always
    ports:
      - 8081:8080
    environment:
      - SEARXNG_BASE_URL=https://searxng.example.com/ # change me
      - SEARXNG_LIMITER=false
      - SEARXNG_SECRET=bOIDTyEIXBWFeGyfaDGU0gSYvniVcCJ6 # change me
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    configs:
      - source: searxng_inline_settings
        target: /etc/searxng/settings.yml
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://127.0.0.1:8080/healthz || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
